//Order Module
export const SET_DATE = 'setDate'
export const ADD_BOOKING = 'addBooking'
export const SET_ID = 'setOrderId'
export const SET_COST = 'setCost'
export const SET_DISCOUNT = 'setDiscount'
export const SET_PAYTYPE = 'setPayType'
export const SET_CLIENT = 'setClient'
export const SET_TYPE = 'setType'
export const SET_STATUS = 'setStatus'
export const REPLACE_BOOKING = 'replaceBooking'
export const SET_ORDER = 'setOrder'

//Booking Module
export const SET_BOOKINGID = 'setBookingId'
export const SET_BOOKINGDISCOUNT = 'setBookingDiscount'
export const ADD_BOOKINGDISCOUNT = 'addBookingDiscount'
export const SET_BOOKINGDATE = 'setBookingDate'
export const SET_BOOKINGTIME = 'setBookingTime'
export const SET_BOOKINGFIELD = 'setBookingField'
export const SET_BOOKINGPAID = 'setBookingPaid'
export const SET_BOOKINGPRICE = 'setBookingPrice'
export const SET_DURATION = 'setDuration'
export const SET_BOOKING = 'setBooking'
